apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: staticweb
  name: staticweb
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: staticweb
  strategy: {}
  template:
    metadata:
      labels:
        app: staticweb
    spec:
      containers:
      - image: rmortale/static-web:sha-d39d5e1
        name: static-web
