---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    fluxcd.io/automated: "true"
  labels:
    app: staticweb
  name: staticweb
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: staticweb
  strategy: {}
  template:
    metadata:
      labels:
        app: staticweb
    spec:
      containers:
      - image: rmortale/static-web:sha-94bad3a
        name: static-web
